// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRaCn97O0ZJz2590LlQL4_yyyUGtWs2Tc',
    appId: '1:443516677156:web:95c1c4775d611ca5473cb1',
    messagingSenderId: '443516677156',
    projectId: 'fir-storage-f43fd',
    authDomain: 'fir-storage-f43fd.firebaseapp.com',
    storageBucket: 'fir-storage-f43fd.appspot.com',
    measurementId: 'G-6RS7Z33XJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQQuWukTTwqua_cxXadXYLmJp6XLL7KBk',
    appId: '1:443516677156:android:bb4b4fe18ecedaf6473cb1',
    messagingSenderId: '443516677156',
    projectId: 'fir-storage-f43fd',
    storageBucket: 'fir-storage-f43fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxq7kmuSjG53h0mJOlUoSgTrlzbQ0KZMQ',
    appId: '1:443516677156:ios:0bfd4d3b5aaa99e6473cb1',
    messagingSenderId: '443516677156',
    projectId: 'fir-storage-f43fd',
    storageBucket: 'fir-storage-f43fd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
